### ISSUE TITLE
Validator node panicked

### ISSUE THREAD

**Issue by StakerSpace** [AcalaNetwork/Acala#113]
Running the docker container for validators, I had the following panic in my logs:
```
====================

Version: 0.2.8-36e791e-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   2: rust_begin_unwind
             at src/libstd/panicking.rs:375
   3: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
   4: core::option::expect_failed
             at src/libcore/option.rs:1188
   5: core::option::Option<T>::expect
             at rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/option.rs:348
      std::time::Instant::duration_since
             at src/libstd/time.rs:261
      <std::time::Instant as core::ops::arith::Sub>::sub
             at src/libstd/time.rs:388
   6: <sc_network::protocol::legacy_proto::behaviour::LegacyProto<TSubstream> as libp2p_swarm::behaviour::NetworkBehaviour>::poll
   7: <sc_network::protocol::Protocol<B,S,H> as libp2p_swarm::behaviour::NetworkBehaviour>::poll
   8: <sc_network::behaviour::Behaviour<B,S,H> as libp2p_swarm::behaviour::NetworkBehaviour>::poll
   9: libp2p_swarm::ExpandedSwarm<TTransport,TBehaviour,TInEvent,TOutEvent,THandler,THandlerErr,TConnInfo>::poll_next_event
  10: futures_util::future::future::FutureExt::poll_unpin
  11: <sc_network::service::NetworkWorker<B,S,H> as core::future::future::Future>::poll
  12: futures_util::future::future::FutureExt::poll_unpin
  13: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  14: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  15: tokio::task::core::Core<T>::poll
  16: std::panicking::try::do_call
  17: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  18: tokio::task::harness::Harness<T,S>::poll
  19: tokio::runtime::thread_pool::worker::GenerationGuard::run_task
  20: tokio::runtime::thread_pool::worker::GenerationGuard::run
  21: std::thread::local::LocalKey<T>::with
  22: tokio::runtime::thread_pool::worker::Worker::run
  23: tokio::task::core::Core<T>::poll
  24: std::panicking::try::do_call
  25: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  26: tokio::task::harness::Harness<T,S>::poll
  27: tokio::runtime::blocking::pool::Inner::run
  28: tokio::runtime::context::enter
  29: std::sys_common::backtrace::__rust_begin_short_backtrace
  30: std::panicking::try::do_call
  31: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  32: core::ops::function::FnOnce::call_once{{vtable.shim}}
  33: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/liballoc/boxed.rs:1022
  34: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/liballoc/boxed.rs:1022
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:80
  35: start_thread
  36: clone


Thread 'main-tokio-' panicked at 'supplied instant is later than self', src/libcore/option.rs:1188
```

**Comment by xlc** [comment]
Thanks for reporting. I believe this is fixed by https://github.com/paritytech/substrate/pull/4951, which will be included in our next release.
