### ISSUE TITLE
Connecting to polkadot.js wallet to apps.acala.network fails if Clover Wallet extension installed in browser

### ISSUE THREAD

**Issue by Redoudou** [AcalaNetwork/Acala#1748]
**Describe the bug**
Impossible to connect polkadot wallet to Acala network.

**Expected Behavior**
When going to https://apps.acala.network and clicking on connect wallet > then selecting polkadot.js it should connect. 

**Current Behavior**

The page freeze indefinitly. 

**Steps to Reproduce**

1. install Clover Wallet : 4.5.3
2. install polkadot{.js} extension 0.42.2
3. Select proper Acala network on polkadot extension
4. go https://apps.acala.network
5. click on connect wallet
6. select polkadot.js

**Additional context**

Brave : Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (arm64)
Clover Wallet : 4.5.3
polkadot{.js} extension 0.42.2
Mac Os : 12.0.1 (21A559)

```
index.js:13 [Redux-LocalStorage-Simple] Invalid load 'redux_localstorage_simple_api.firstEndpoint' provided. Check your 'states' in 'load()'. If this is your first time running this app you may see this message. To disable it in future use the 'disableWarnings' flag, see documentation.
p @ index.js:13
index.js:393 WebSocket connection to 'wss://acala-polkadot.api.onfinality.io/' failed: 
(anonymous) @ index.js:393
instrument.ts:129 2022-01-04 22:03:27          API-WS: disconnected from wss://acala-polkadot.api.onfinality.io: 1006:: Abnormal Closure
(anonymous) @ instrument.ts:129
instrument.ts:129 set homa lite sdk
instrument.ts:129 2022-01-04 22:14:08          API-WS: disconnected from wss://rpc.polkadot.io: 1006:: Abnormal Closure
(anonymous) @ instrument.ts:129
index.js:400 WebSocket connection to 'wss://polkadot.api.onfinality.io/' failed: 
(anonymous) @ index.js:400
instrument.ts:129 2022-01-04 22:14:11          API-WS: disconnected from wss://polkadot.api.onfinality.io: 1006:: Abnormal Closure
(anonymous) @ instrument.ts:129
instrument.ts:129 2022-01-04 22:16:09          API-WS: disconnected from wss://rpc.polkadot.io: 1006:: Abnormal Closure
(anonymous) @ instrument.ts:129
index.js:400 WebSocket connection to 'wss://polkadot.api.onfinality.io/' failed: 
(anonymous) @ index.js:400
instrument.ts:129 2022-01-04 22:16:12          API-WS: disconnected from wss://polkadot.api.onfinality.io: 1006:: Abnormal Closure
(anonymous) @ instrument.ts:129
instrument.ts:129 2022-01-04 22:18:08          API-WS: disconnected from wss://rpc.polkadot.io: 1006:: Abnormal Closure
(anonymous) @ instrument.ts:129
index.js:400 WebSocket connection to 'wss://polkadot.api.onfinality.io/' failed: 
(anonymous) @ index.js:400
instrument.ts:129 2022-01-04 22:18:11          API-WS: disconnected from wss://polkadot.api.onfinality.io: 1006:: Abnormal Closure
(anonymous) @ instrument.ts:129
instrument.ts:129 2022-01-04 22:20:09          API-WS: disconnected from wss://rpc.polkadot.io: 1006:: Abnormal Closure
(anonymous) @ instrument.ts:129
index.js:400 WebSocket connection to 'wss://polkadot.api.onfinality.io/' failed: 
(anonymous) @ index.js:400
instrument.ts:129 2022-01-04 22:20:12          API-WS: disconnected from wss://polkadot.api.onfinality.io: 1006:: Abnormal Closure
(anonymous) @ instrument.ts:129
instrument.ts:129 2022-01-04 22:22:08          API-WS: disconnected from wss://rpc.polkadot.io: 1006:: Abnormal Closure
(anonymous) @ instrument.ts:129
index.js:400 WebSocket connection to 'wss://polkadot.api.onfinality.io/' failed: 
(anonymous) @ index.js:400
instrument.ts:129 2022-01-04 22:22:11          API-WS: disconnected from wss://polkadot.api.onfinality.io: 1006:: Abnormal Closure
(anonymous) @ instrument.ts:129
instrument.ts:129 2022-01-04 22:24:08          API-WS: disconnected from wss://rpc.polkadot.io: 1006:: Abnormal Closure
(anonymous) @ instrument.ts:129
index.js:400 WebSocket connection to 'wss://polkadot.api.onfinality.io/' failed: 
(anonymous) @ index.js:400
instrument.ts:129 2022-01-04 22:24:11          API-WS: disconnected from wss://polkadot.api.onfinality.io: 1006:: Abnormal Closure
(anonymous) @ instrument.ts:129
instrument.ts:129 2022-01-04 22:26:08          API-WS: disconnected from wss://rpc.polkadot.io: 1006:: Abnormal Closure
(anonymous) @ instrument.ts:129
index.js:400 WebSocket connection to 'wss://polkadot.api.onfinality.io/' failed: 
(anonymous) @ index.js:400
instrument.ts:129 2022-01-04 22:26:12          API-WS: disconnected from wss://polkadot.api.onfinality.io: 1006:: Abnormal Closure
(anonymous) @ instrument.ts:129
inpage.js:1 Clover: Lost connection to "Clover".
Error
    at new CloverInpageProvider (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:1:18293)
    at r.initializeProvider (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:1:26608)
    at S (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:1:10956)
    at Object.<anonymous> (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:1:10717)
    at Object.<anonymous> (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:1:14247)
    at Object.8../clover/contentScript/messaging/in-page (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:1:14260)
    at o (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:1:254)
    at e (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:1:414)
    at chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:1:431
r.logStreamDisconnectWarning @ inpage.js:1
inpage.js:1 Error: Clover: Disconnected from Clover background. Page reload required.
    at CloverInpageProvider._handleDisconnect (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:1)
    at CloverInpageProvider._handleStreamDisconnect (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:1)
    at chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:17
    at t (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:17)
    at i.<anonymous> (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:17)
    at i.t (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:17)
    at i.h (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:8)
    at f (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:8)
    at i.a.emit (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:8)
    at P (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:17)
    at chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:17
    at i.m.end (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:17)
    at i.f._destroy (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:17)
    at i.destroy (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:17)
    at i.<anonymous> (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:1)
    at o (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:1)
    at i.emit (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:1)
    at chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:1
    at f.write [as _write] (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:1)
    at y (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:17)
    at chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:17
    at f.m.write (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:17)
    at o.g (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:17)
    at d (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:8)
    at o.a.emit (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:8)
    at S (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:17)
    at w (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:17)
    at o.y.push (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:17)
    at c._write (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:1)
    at y (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:17)
    at chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:17
    at c.m.write (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:17)
    at i.g (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:17)
    at d (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:8)
    at i.a.emit (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:8)
    at S (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:17)
    at w (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:17)
    at i.y.push (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:17)
    at i._onMessage (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:17)
_handleDisconnect @ inpage.js:1
inpage.js:1 Clover: Lost connection to "Clover RpcProvider".
Error
    at new CloverInpageProvider (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:1:18525)
    at r.initializeProvider (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:1:26608)
    at S (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:1:10956)
    at Object.<anonymous> (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:1:10717)
    at Object.<anonymous> (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:1:14247)
    at Object.8../clover/contentScript/messaging/in-page (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:1:14260)
    at o (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:1:254)
    at e (chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:1:414)
    at chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/inpage.js:1:431
r.logStreamDisconnectWarning @ inpage.js:1
instrument.ts:129 2022-01-04 22:34:08          API-WS: disconnected from wss://rpc.polkadot.io: 1006:: Abnormal Closure
(anonymous) @ instrument.ts:129
index.js:400 WebSocket connection to 'wss://polkadot.api.onfinality.io/' failed: 
(anonymous) @ index.js:400
instrument.ts:129 2022-01-04 22:34:11          API-WS: disconnected from wss://polkadot.api.onfinality.io: 1006:: Abnormal Closure
(anonymous) @ instrument.ts:129
instrument.ts:129 2022-01-04 22:36:08          API-WS: disconnected from wss://rpc.polkadot.io: 1006:: Abnormal Closure
(anonymous) @ instrument.ts:129
index.js:400 WebSocket connection to 'wss://polkadot.api.onfinality.io/' failed: 
(anonymous) @ index.js:400
instrument.ts:129 2022-01-04 22:36:12          API-WS: disconnected from wss://polkadot.api.onfinality.io: 1006:: Abnormal Closure
(anonymous) @ instrument.ts:129
instrument.ts:129 2022-01-04 22:38:08          API-WS: disconnected from wss://rpc.polkadot.io: 1006:: Abnormal Closure
(anonymous) @ instrument.ts:129
instrument.ts:129 2022-01-04 22:38:08        RPC-CORE: health(): Health:: disconnected from wss://rpc.polkadot.io: 1006:: Abnormal Closure
(anonymous) @ instrument.ts:129
index.js:400 WebSocket connection to 'wss://polkadot.api.onfinality.io/' failed: 
(anonymous) @ index.js:400
instrument.ts:129 2022-01-04 22:38:11          API-WS: disconnected from wss://polkadot.api.onfinality.io: 1006:: Abnormal Closure
(anonymous) @ instrument.ts:129
instrument.ts:129 2022-01-04 22:40:09          API-WS: disconnected from wss://rpc.polkadot.io: 1006:: Abnormal Closure
(anonymous) @ instrument.ts:129
index.js:400 WebSocket connection to 'wss://polkadot.api.onfinality.io/' failed: 
(anonymous) @ index.js:400
instrument.ts:129 2022-01-04 22:40:12          API-WS: disconnected from wss://polkadot.api.onfinality.io: 1006:: Abnormal Closure
(anonymous) @ instrument.ts:129
instrument.ts:129 2022-01-04 22:42:08          API-WS: disconnected from wss://rpc.polkadot.io: 1006:: Abnormal Closure
(anonymous) @ instrument.ts:129
index.js:400 WebSocket connection to 'wss://polkadot.api.onfinality.io/' failed: 
(anonymous) @ index.js:400
instrument.ts:129 2022-01-04 22:42:11          API-WS: disconnected from wss://polkadot.api.onfinality.io: 1006:: Abnormal Closure
(anonymous) @ instrument.ts:129
DevTools failed to load source map: Could not load content for chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/scripts/common.bundle.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/scripts/8913.bundle.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/scripts/content.bundle.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://nhnkbkgjikgcigadomkphalanndcapjk/sourcemaps/inpage.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

**Comment by xlc** [comment]
Clover Wallet is not supported and we do not have capacity to support it at this stage.
It is also likely the issue is on Clover Wallet side instead of Acala dApp side.

**Comment by Redoudou** [comment]
The problem is that if I have clover wallet and polkadot.js installed in my browser, I need to dis-activate clover wallet to connect to Acala maybe this should be mentioned somewhere.
