### ISSUE TITLE
Division by zero panic (EVM)

### ISSUE THREAD

**Issue by boyswan** [AcalaNetwork/Acala#790]
Reporting a bug, will update with more info once I can reliably replicate

```
Version: 0.7.3-98db5f0-x86_64-macos

   0: backtrace::backtrace::libunwind::trace
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/backtrace/libunwind.rs:90:5
      backtrace::backtrace::trace_unsynchronized
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/backtrace/mod.rs:66:5
   1: backtrace::backtrace::trace
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/backtrace/mod.rs:53:14
   2: backtrace::capture::Backtrace::create
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/capture.rs:176:9
   3: backtrace::capture::Backtrace::new
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/capture.rs:140:22
   4: sp_panic_handler::panic_hook
             at /Users/jack/.cargo/git/checkouts/substrate-7e08433d4c370a21/e03ca38/primitives/panic-handler/src/lib.rs:150:18
   5: sp_panic_handler::set::{{closure}}
             at /Users/jack/.cargo/git/checkouts/substrate-7e08433d4c370a21/e03ca38/primitives/panic-handler/src/lib.rs:60:4
   6: std::panicking::rust_panic_with_hook
             at /rustc/e37a13cc3594004663738bd18d8100e6db9666cf/library/std/src/panicking.rs:595:17
   7: std::panicking::begin_panic::{{closure}}
             at /Users/jack/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:520:9
   8: std::sys_common::backtrace::__rust_end_short_backtrace
             at /Users/jack/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:141:18
   9: std::panicking::begin_panic
             at /Users/jack/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:519:12
  10: primitive_types::U256::div_mod
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/uint-0.9.0/src/uint.rs:959:5
  11: <primitive_types::U256 as core::ops::arith::Div<T>>::div
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/uint-0.9.0/src/uint.rs:1433:5
  12: <evm_rpc::EVMApi<B,C,Balance> as evm_rpc::evm_api::rpc_impl_EVMApi::gen_server::EVMApi<B>>::estimate_gas
             at modules/evm/rpc/src/lib.rs:272:20
  13: evm_rpc::evm_api::rpc_impl_EVMApi::gen_server::EVMApi::to_delegate::{{closure}}
             at modules/evm/rpc/src/evm_api.rs:13:1
  14: <jsonrpc_core::delegates::DelegateAsyncMethod<T,F> as jsonrpc_core::calls::RpcMethod<M>>::call
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/jsonrpc-core-15.1.0/src/delegates.rs:27:12
  15: jsonrpc_core::io::MetaIoHandler<T,S>::handle_call::{{closure}}::{{closure}}::{{closure}}
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/jsonrpc-core-15.1.0/src/io.rs:264:28
  16: futures::future::lazy::Lazy<F,R>::get
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.30/src/future/lazy.rs:64:59
  17: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.30/src/future/lazy.rs:82:9
  18: futures::future::chain::Chain<A,B,C>::poll
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.30/src/future/chain.rs:26:23
  19: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.30/src/future/then.rs:32:9
  20: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.30/src/future/mod.rs:113:13
  21: <futures::future::either::Either<A,B> as futures::future::Future>::poll
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.30/src/future/either.rs:35:37
  22: <futures::future::either::Either<A,B> as futures::future::Future>::poll
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.30/src/future/either.rs:36:37
  23: <futures::future::map::Map<A,F> as futures::future::Future>::poll
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.30/src/future/map.rs:30:23
  24: <futures::future::either::Either<A,B> as futures::future::Future>::poll
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.30/src/future/either.rs:35:37
  25: <futures::future::either::Either<A,B> as futures::future::Future>::poll
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.30/src/future/either.rs:36:37
  26: <futures::future::either::Either<A,B> as futures::future::Future>::poll
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.30/src/future/either.rs:36:37
  27: <futures::future::map::Map<A,F> as futures::future::Future>::poll
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.30/src/future/map.rs:30:23
  28: <futures::future::map::Map<A,F> as futures::future::Future>::poll
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.30/src/future/map.rs:30:23
  29: <futures::future::select::Select<A,B> as futures::future::Future>::poll
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.30/src/future/select.rs:48:23
  30: <futures::future::map::Map<A,F> as futures::future::Future>::poll
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.30/src/future/map.rs:30:23
  31: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.30/src/future/map_err.rs:30:23
  32: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.30/src/future/mod.rs:113:13
  33: futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.30/src/task_impl/mod.rs:329:45
  34: futures::task_impl::Spawn<T>::enter::{{closure}}
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.30/src/task_impl/mod.rs:399:27
  35: futures::task_impl::std::set
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.30/src/task_impl/std/mod.rs:86:13
  36: futures::task_impl::Spawn<T>::enter
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.30/src/task_impl/mod.rs:399:9
  37: futures::task_impl::Spawn<T>::poll_fn_notify
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.30/src/task_impl/mod.rs:291:9
  38: futures::task_impl::Spawn<T>::poll_future_notify
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.30/src/task_impl/mod.rs:329:9
  39: tokio_threadpool::task::Task::run::{{closure}}
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/task/mod.rs:145:17
  40: core::ops::function::FnOnce::call_once
             at /Users/jack/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  41: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /Users/jack/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  42: std::panicking::try::do_call
             at /Users/jack/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  43: ___rust_try
  44: std::panicking::try
             at /Users/jack/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  45: std::panic::catch_unwind
             at /Users/jack/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  46: tokio_threadpool::task::Task::run
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/task/mod.rs:130:19
  47: tokio_threadpool::worker::Worker::run_task2
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/worker/mod.rs:567:9
  48: tokio_threadpool::worker::Worker::run_task
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/worker/mod.rs:459:19
  49: tokio_threadpool::worker::Worker::try_run_owned_task
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/worker/mod.rs:390:17
  50: tokio_threadpool::worker::Worker::try_run_task
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/worker/mod.rs:297:12
  51: tokio_threadpool::worker::Worker::run
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/worker/mod.rs:241:16
  52: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:390:29
  53: tokio_timer::timer::handle::with_default
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.13/src/timer/handle.rs:74:5
  54: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:382:25
  55: tokio_timer::clock::clock::with_default
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.13/src/clock/clock.rs:125:5
  56: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:381:21
  57: tokio_reactor::with_default
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.12/src/lib.rs:220:5
  58: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:380:17
  59: tokio_threadpool::callback::Callback::call
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/callback.rs:22:9
  60: tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}}
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/worker/mod.rs:127:21
  61: tokio_executor::global::with_default::{{closure}}
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.10/src/global.rs:221:9
  62: std::thread::local::LocalKey<T>::try_with
             at /Users/jack/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  63: std::thread::local::LocalKey<T>::with
             at /Users/jack/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  64: tokio_executor::global::with_default
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.10/src/global.rs:190:5
  65: tokio_threadpool::worker::Worker::do_run::{{closure}}
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/worker/mod.rs:125:13
  66: std::thread::local::LocalKey<T>::try_with
             at /Users/jack/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  67: std::thread::local::LocalKey<T>::with
             at /Users/jack/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  68: tokio_threadpool::worker::Worker::do_run
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/worker/mod.rs:116:9
  69: tokio_threadpool::pool::Pool::spawn_thread::{{closure}}
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/pool/mod.rs:345:21
  70: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /Users/jack/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  71: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /Users/jack/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/mod.rs:474:17
  72: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /Users/jack/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  73: std::panicking::try::do_call
             at /Users/jack/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  74: ___rust_try
  75: std::panicking::try
             at /Users/jack/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  76: std::panic::catch_unwind
             at /Users/jack/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  77: std::thread::Builder::spawn_unchecked::{{closure}}
             at /Users/jack/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/mod.rs:473:30
  78: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /Users/jack/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  79: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/e37a13cc3594004663738bd18d8100e6db9666cf/library/alloc/src/boxed.rs:1546:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/e37a13cc3594004663738bd18d8100e6db9666cf/library/alloc/src/boxed.rs:1546:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/e37a13cc3594004663738bd18d8100e6db9666cf/library/std/src/sys/unix/thread.rs:71:17
  80: __pthread_body
  81: __pthread_start


Thread 'event.loop0' panicked at 'division by zero', /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/primitive-types-0.9.0/src/lib.rs:38

This is a bug. Please report it at:

	https://github.com/AcalaNetwork/Acala/issues
```

**Comment by Netherdrake** [comment]
Sometimes `calculate_gas_used` returns Ok(0) causing division by 0 error on:
```
    change_pct = (U256::from(100) * (old_best - best)) / old_best;
```
It is essentially possible to do denial-of-service on node by calling `estimate_gas`.

**Comment by zjb0807** [comment]
@boyswan Can you show me your contract?

I can't reproduce the `used_gas = 0`.
```
pragma solidity ^0.6.0;

contract Tests {
    function get() public {}
}
```

**Comment by Netherdrake** [comment]
I am guessing it could be from using a predeploy contract on an address that does not exist (there were some address changes recently on precompile tokens etc.). Im not sure if this even makes sense, just a speculation.

**Comment by zjb0807** [comment]
If the EVM execute failed, it returns `Revert(Reverted)`.

I had tried the `selfdestruct`, but can't reproduce it.

**Comment by boyswan** [comment]
Apologies - I'm struggling to reproduce it myself and don't have reference to the original code. @Netherdrake was correct in that I was interacting with predeploy contracts, and AFAIK it was happening when I was calling ERC20.approve. 

Sorry I can't be of more help - if I think of anything I'll make sure to update here.

**Comment by Netherdrake** [comment]
Yeah I ran into the same issue deploying uniswap. The contracts deployed fine, but it crashed the node on `approve` call here:
https://github.com/AcalaNetwork/evm-examples/blob/master/uniswap/src/deploy.ts#L29

On latest master of every repo it crashes but with different error. Anyway, the point is, the Acala node is DoS-able under some conditions.

**Comment by zjb0807** [comment]
Because moditied every token decimail, so the amount too large. I fixed it.
https://github.com/AcalaNetwork/evm-examples/blob/dd3b2ff69a9467301cece34233b1b9ccf7b95d29/uniswap/src/deploy.ts#L8
