### ISSUE TITLE
Crash on long time running

### ISSUE THREAD

**Issue by jasl** [AcalaNetwork/Acala#851]
I'm running Acala as parachain (using `dev` chainspec), Relaychain using latest Polkadot `rococo-v1` branch, using `polkadot-launch` to deploy the environment

After about 1 day, I check logs and found Acala crashed.

Crash log below

```
Version: 0.7.11-022f632-x86_64-linux-gnu

   0: sp_panic_handler::panic_hook
             at /home/jasl/.cargo/git/checkouts/substrate-7e08433d4c370a21/1404f2a/primitives/panic-handler/src/lib.rs:150:18
   1: sp_panic_handler::set::{{closure}}
             at /home/jasl/.cargo/git/checkouts/substrate-7e08433d4c370a21/1404f2a/primitives/panic-handler/src/lib.rs:60:4
   2: std::panicking::rust_panic_with_hook
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:595:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:495:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:141:18
   5: rust_begin_unwind
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:493:5
   6: core::panicking::panic_fmt
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/panicking.rs:92:14
   7: core::panicking::panic
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/panicking.rs:50:5
   8: <sc_network::protocol::notifications::behaviour::Notifications as libp2p_swarm::behaviour::NetworkBehaviour>::inject_event
             at /home/jasl/.cargo/git/checkouts/substrate-7e08433d4c370a21/1404f2a/client/network/src/protocol/notifications/behaviour.rs:1720:7
   9: <sc_network::protocol::Protocol<B> as libp2p_swarm::behaviour::NetworkBehaviour>::inject_event
             at /home/jasl/.cargo/git/checkouts/substrate-7e08433d4c370a21/1404f2a/client/network/src/protocol.rs:1205:3
  10: <sc_network::behaviour::Behaviour<B> as libp2p_swarm::behaviour::NetworkBehaviour>::inject_event
             at /home/jasl/.cargo/git/checkouts/substrate-7e08433d4c370a21/1404f2a/client/network/src/behaviour.rs:55:10
  11: libp2p_swarm::ExpandedSwarm<TBehaviour,TInEvent,TOutEvent,THandler>::poll_next_event
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-swarm-0.27.2/src/lib.rs:509:21
  12: libp2p_swarm::ExpandedSwarm<TBehaviour,TInEvent,TOutEvent,THandler>::next_event::{{closure}}::{{closure}}
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-swarm-0.27.2/src/lib.rs:475:35
  13: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/poll_fn.rs:55:9
  14: libp2p_swarm::ExpandedSwarm<TBehaviour,TInEvent,TOutEvent,THandler>::next_event::{{closure}}
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-swarm-0.27.2/src/lib.rs:475:9
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/mod.rs:80:19
  16: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/future.rs:119:9
  17: futures_util::future::future::FutureExt::poll_unpin
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/future/mod.rs:562:9
  18: <sc_network::service::NetworkWorker<B,H> as core::future::future::Future>::poll
             at /home/jasl/.cargo/git/checkouts/substrate-7e08433d4c370a21/1404f2a/client/network/src/service.rs:1445:21
  19: <&mut F as core::future::future::Future>::poll
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/future.rs:107:9
  20: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/future/fuse.rs:86:37
  21: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/future.rs:119:9
  22: futures_util::future::future::FutureExt::poll_unpin
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/future/mod.rs:562:9
  23: sc_service::build_network_future::{{closure}}::{{closure}}::{{closure}}
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/async_await/select_mod.rs:326:13
  24: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/ops/function.rs:269:13
  25: sc_service::build_network_future::{{closure}}::{{closure}}
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/async_await/select_mod.rs:326:13
  26: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/poll_fn.rs:55:9
  27: sc_service::build_network_future::{{closure}}
             at /home/jasl/.cargo/git/checkouts/substrate-7e08433d4c370a21/1404f2a/client/service/src/lib.rs:226:3
  28: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/mod.rs:80:19
  29: sc_service::builder::build_network::{{closure}}
             at /home/jasl/.cargo/git/checkouts/substrate-7e08433d4c370a21/1404f2a/client/service/src/builder.rs:995:3
  30: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/mod.rs:80:19
  31: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
             at /home/jasl/.cargo/git/checkouts/substrate-7e08433d4c370a21/1404f2a/client/service/src/task_manager/prometheus_future.rs:61:3
  32: <std::panic::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panic.rs:361:9
  33: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/future/catch_unwind.rs:32:42
  34: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panic.rs:344:9
  35: std::panicking::try::do_call
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:379:40
  36: __rust_try
  37: std::panicking::try
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:343:19
  38: std::panic::catch_unwind
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panic.rs:431:14
  39: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/future/catch_unwind.rs:32:9
  40: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/future.rs:119:9
  41: futures_util::future::future::FutureExt::poll_unpin
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/future/mod.rs:562:9
  42: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/select.rs:101:36
  43: sc_service::task_manager::SpawnTaskHandle::spawn_inner::{{closure}}
             at /home/jasl/.cargo/git/checkouts/substrate-7e08433d4c370a21/1404f2a/client/service/src/task_manager/mod.rs:105:11
  44: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/mod.rs:80:19
  45: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-futures-0.2.5/src/lib.rs:283:9
  46: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/future.rs:119:9
  47: futures_executor::local_pool::block_on::{{closure}}
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.13/src/local_pool.rs:317:23
  48: futures_executor::local_pool::run_executor::{{closure}}
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.13/src/local_pool.rs:87:37
  49: std::thread::local::LocalKey<T>::try_with
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/thread/local.rs:272:16
  50: std::thread::local::LocalKey<T>::with
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/thread/local.rs:248:9
  51: futures_executor::local_pool::run_executor
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.13/src/local_pool.rs:83:5
  52: futures_executor::local_pool::block_on
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.13/src/local_pool.rs:317:5
  53: sc_cli::runner::Runner<C>::new::{{closure}}::{{closure}}
             at /home/jasl/.cargo/git/checkouts/substrate-7e08433d4c370a21/1404f2a/client/cli/src/runner.rs:133:44
  54: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/task.rs:41:21
  55: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:173:17
  56: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/loom/std/unsafe_cell.rs:14:9
  57: tokio::runtime::task::core::Core<T,S>::poll
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:158:13
  58: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:107:27
  59: core::ops::function::FnOnce::call_once
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/ops/function.rs:227:5
  60: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panic.rs:344:9
  61: std::panicking::try::do_call
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:379:40
  62: __rust_try
  63: std::panicking::try
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:343:19
  64: std::panic::catch_unwind
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panic.rs:431:14
  65: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:89:19
  66: tokio::runtime::task::raw::poll
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:104:5
  67: tokio::runtime::task::raw::RawTask::poll
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:66:18
  68: tokio::runtime::task::Notified<S>::run
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/mod.rs:169:9
  69: tokio::runtime::blocking::pool::Inner::run
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/pool.rs:250:17
  70: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::{{closure}}
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/pool.rs:230:21
  71: tokio::runtime::context::enter
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/context.rs:72:5
  72: tokio::runtime::handle::Handle::enter
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/handle.rs:76:9
  73: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/jasl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/pool.rs:229:17
  74: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:125:18
  75: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/thread/mod.rs:474:17
  76: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panic.rs:344:9
  77: std::panicking::try::do_call
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:379:40
  78: __rust_try
  79: std::panicking::try
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:343:19
  80: std::panic::catch_unwind
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panic.rs:431:14
  81: std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/thread/mod.rs:473:30
  82: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/ops/function.rs:227:5
  83: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/alloc/src/boxed.rs:1546:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/alloc/src/boxed.rs:1546:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys/unix/thread.rs:71:17
  84: start_thread
  85: clone


Thread 'tokio-runtime-worker' panicked at 'assertion failed: false', /home/jasl/.cargo/git/checkouts/substrate-7e08433d4c370a21/1404f2a/client/network/src/protocol/notifications/behaviour.rs:1720
```

**Comment by xlc** [comment]
This is a Substrate issue.

**Comment by xlc** [comment]
closed as this is upstream issue
