### ISSUE TITLE
Syncing panics.

### ISSUE THREAD

**Issue by zie1ony** [AcalaNetwork/Acala#872]
I got this error when syncing.

```
2021-04-07 18:02:00 [Relaychain] Failed to request addresses of authorities: CallingRuntime(RuntimeApiError(Application(Execution(RuntimePanicked("assertion failed: res.is_ok()")))))    

====================

Version: 0.7.11-dae608a-x86_64-linux-gnu

   0: sp_panic_handler::panic_hook
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/primitives/panic-handler/src/lib.rs:150:18
   1: sp_panic_handler::set::{{closure}}
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/primitives/panic-handler/src/lib.rs:60:4
   2: std::panicking::rust_panic_with_hook
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:595:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:495:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:141:18
   5: rust_begin_unwind
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:493:5
   6: core::panicking::panic_fmt
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/panicking.rs:92:14
   7: core::panicking::panic
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/panicking.rs:50:5
   8: polkadot_runtime_common::slots::Module<T>::manage_lease_period_start
             at /home/ziel/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/80235e9/runtime/common/src/slots.rs:284:5
   9: <polkadot_runtime_common::slots::Module<T> as frame_support::traits::OnInitialize<<T as frame_system::pallet::Config>::BlockNumber>>::on_initialize
             at /home/ziel/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/80235e9/runtime/common/src/slots.rs:153:5
  10: <(TupleElement0,TupleElement1) as frame_support::traits::OnInitialize<BlockNumber>>::on_initialize
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/frame/support/src/traits.rs:1597:1
  11: <(TupleElement0,TupleElement1) as frame_support::traits::OnInitialize<BlockNumber>>::on_initialize
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/frame/support/src/traits.rs:1597:1
  12: <(TupleElement0,TupleElement1) as frame_support::traits::OnInitialize<BlockNumber>>::on_initialize
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/frame/support/src/traits.rs:1597:1
  13: <(TupleElement0,TupleElement1) as frame_support::traits::OnInitialize<BlockNumber>>::on_initialize
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/frame/support/src/traits.rs:1597:1
  14: <(TupleElement0,TupleElement1) as frame_support::traits::OnInitialize<BlockNumber>>::on_initialize
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/frame/support/src/traits.rs:1597:1
  15: <(TupleElement0,TupleElement1) as frame_support::traits::OnInitialize<BlockNumber>>::on_initialize
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/frame/support/src/traits.rs:1597:1
  16: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::initialize_block_impl
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/frame/executive/src/lib.rs:278:4
  17: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::initialize_block
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/frame/executive/src/lib.rs:242:3
  18: <rococo_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<sp_runtime::multiaddress::MultiAddress<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,()>,rococo_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<rococo_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<rococo_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<rococo_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<rococo_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<rococo_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<rococo_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<rococo_runtime::Runtime>)>>>>::initialize_block
             at /home/ziel/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/80235e9/runtime/rococo/src/lib.rs:762:4
  19: sp_api::runtime_decl_for_Core::initialize_block_native_call_generator::{{closure}}
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/primitives/api/src/lib.rs:650:1
  20: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call::{{closure}}::{{closure}}
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/client/service/src/client/call_executor.rs:253:29
  21: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call::{{closure}}::{{closure}}
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/client/executor/src/native_executor.rs:514:61
  22: std::panicking::try::do_call
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:379:40
  23: __rust_try
  24: std::panicking::try
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:343:19
  25: std::panic::catch_unwind
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panic.rs:431:14
  26: sc_executor::native_executor::with_externalities_safe::{{closure}}
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/client/executor/src/native_executor.rs:62:4
  27: environmental::using::{{closure}}
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.1.2/src/lib.rs:126:3
  28: std::thread::local::LocalKey<T>::try_with
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/thread/local.rs:272:16
  29: std::thread::local::LocalKey<T>::with
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/thread/local.rs:248:9
  30: environmental::using
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.1.2/src/lib.rs:107:2
  31: sp_externalities::scope_limited::ext::using
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.1.2/src/lib.rs:253:5
  32: sp_externalities::scope_limited::set_and_run_with_externalities
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/primitives/externalities/src/scope_limited.rs:30:2
  33: sc_executor::native_executor::with_externalities_safe
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/client/executor/src/native_executor.rs:56:2
  34: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call::{{closure}}
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/client/executor/src/native_executor.rs:514:17
  35: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/client/executor/src/native_executor.rs:184:5
  36: sc_executor::wasm_runtime::VersionedRuntime::with_instance
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/client/executor/src/wasm_runtime.rs:94:18
  37: sc_executor::wasm_runtime::RuntimeCache::with_instance
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/client/executor/src/wasm_runtime.rs:273:6
  38: sc_executor::native_executor::WasmExecutor::with_instance
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/client/executor/src/native_executor.rs:173:9
  39: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/client/executor/src/native_executor.rs:470:16
  40: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/primitives/state-machine/src/lib.rs:424:31
  41: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/primitives/state-machine/src/lib.rs:556:7
  42: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/client/service/src/client/call_executor.rs:251:5
  43: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/client/service/src/client/client.rs:1673:3
  44: sp_api::runtime_decl_for_Core::initialize_block_call_api_at
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/primitives/api/src/lib.rs:650:1
  45: <rococo_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::Core_initialize_block_runtime_api_impl::{{closure}}
             at /home/ziel/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/80235e9/runtime/rococo/src/lib.rs:751:1
  46: rococo_runtime::RuntimeApiImpl<Block,C>::call_api_at
             at /home/ziel/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/80235e9/runtime/rococo/src/lib.rs:751:1
  47: <rococo_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::Core_initialize_block_runtime_api_impl
             at /home/ziel/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/80235e9/runtime/rococo/src/lib.rs:751:1
  48: sp_api::Core::initialize_block
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/primitives/api/src/lib.rs:650:1
  49: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at::{{closure}}
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/client/service/src/client/client.rs:1674:7
  50: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/client/service/src/client/call_executor.rs:184:5
  51: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/client/service/src/client/client.rs:1673:3
  52: sp_authority_discovery::runtime_decl_for_AuthorityDiscoveryApi::authorities_call_api_at
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/primitives/authority-discovery/src/lib.rs:44:1
  53: <rococo_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_authority_discovery::AuthorityDiscoveryApi<__SR_API_BLOCK__>>::AuthorityDiscoveryApi_authorities_runtime_api_impl::{{closure}}
             at /home/ziel/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/80235e9/runtime/rococo/src/lib.rs:751:1
  54: rococo_runtime::RuntimeApiImpl<Block,C>::call_api_at
             at /home/ziel/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/80235e9/runtime/rococo/src/lib.rs:751:1
  55: <rococo_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_authority_discovery::AuthorityDiscoveryApi<__SR_API_BLOCK__>>::AuthorityDiscoveryApi_authorities_runtime_api_impl
             at /home/ziel/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/80235e9/runtime/rococo/src/lib.rs:751:1
  56: sp_authority_discovery::AuthorityDiscoveryApi::authorities
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/primitives/authority-discovery/src/lib.rs:44:1
  57: sc_authority_discovery::worker::Worker<Client,Network,Block,DhtEventStream>::refill_pending_lookups_queue::{{closure}}
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/client/authority-discovery/src/worker.rs:331:25
  58: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/mod.rs:80:19
  59: sc_authority_discovery::worker::Worker<Client,Network,Block,DhtEventStream>::run::{{closure}}
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/client/authority-discovery/src/worker.rs:225:22
  60: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/mod.rs:80:19
  61: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/client/service/src/task_manager/prometheus_future.rs:61:3
  62: <std::panic::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panic.rs:361:9
  63: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/future/catch_unwind.rs:32:42
  64: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panic.rs:344:9
  65: std::panicking::try::do_call
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:379:40
  66: __rust_try
  67: std::panicking::try
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:343:19
  68: std::panic::catch_unwind
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panic.rs:431:14
  69: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/future/catch_unwind.rs:32:9
  70: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/future.rs:119:9
  71: futures_util::future::future::FutureExt::poll_unpin
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/future/mod.rs:562:9
  72: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/select.rs:101:36
  73: sc_service::task_manager::SpawnTaskHandle::spawn_inner::{{closure}}
             at /home/ziel/.cargo/git/checkouts/substrate-7e08433d4c370a21/0c26d7b/client/service/src/task_manager/mod.rs:105:11
  74: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/mod.rs:80:19
  75: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-futures-0.2.5/src/lib.rs:283:9
  76: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/future/future.rs:119:9
  77: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:173:17
  78: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/loom/std/unsafe_cell.rs:14:9
  79: tokio::runtime::task::core::Core<T,S>::poll
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:158:13
  80: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:107:27
  81: core::ops::function::FnOnce::call_once
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/ops/function.rs:227:5
  82: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panic.rs:344:9
  83: std::panicking::try::do_call
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:379:40
  84: __rust_try
  85: std::panicking::try
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:343:19
  86: std::panic::catch_unwind
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panic.rs:431:14
  87: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:89:19
  88: tokio::runtime::task::raw::poll
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:104:5
  89: tokio::runtime::task::raw::RawTask::poll
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:66:18
  90: tokio::runtime::task::Notified<S>::run
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/mod.rs:169:9
  91: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:349:13
  92: tokio::coop::with_budget::{{closure}}
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:127:9
  93: std::thread::local::LocalKey<T>::try_with
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/thread/local.rs:272:16
  94: std::thread::local::LocalKey<T>::with
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/thread/local.rs:248:9
  95: tokio::coop::with_budget
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:120:5
      tokio::coop::budget
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:96:5
      tokio::runtime::thread_pool::worker::Context::run_task
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:348:9
  96: tokio::runtime::thread_pool::worker::Context::run
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:320:24
  97: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:305:17
  98: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/macros/scoped_tls.rs:63:9
  99: tokio::runtime::thread_pool::worker::run
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:302:5
 100: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:281:45
 101: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/task.rs:41:21
 102: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:173:17
 103: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/loom/std/unsafe_cell.rs:14:9
 104: tokio::runtime::task::core::Core<T,S>::poll
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:158:13
 105: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:107:27
 106: core::ops::function::FnOnce::call_once
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/ops/function.rs:227:5
 107: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panic.rs:344:9
 108: std::panicking::try::do_call
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:379:40
 109: __rust_try
 110: std::panicking::try
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:343:19
 111: std::panic::catch_unwind
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panic.rs:431:14
 112: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:89:19
 113: tokio::runtime::task::raw::poll
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:104:5
 114: tokio::runtime::task::raw::RawTask::poll
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:66:18
 115: tokio::runtime::task::Notified<S>::run
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/mod.rs:169:9
 116: tokio::runtime::blocking::pool::Inner::run
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/pool.rs:250:17
 117: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::{{closure}}
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/pool.rs:230:21
 118: tokio::runtime::context::enter
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/context.rs:72:5
 119: tokio::runtime::handle::Handle::enter
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/handle.rs:76:9
 120: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/ziel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/pool.rs:229:17
 121: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:125:18
 122: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/thread/mod.rs:474:17
 123: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panic.rs:344:9
 124: std::panicking::try::do_call
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:379:40
 125: __rust_try
 126: std::panicking::try
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:343:19
 127: std::panic::catch_unwind
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panic.rs:431:14
 128: std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/thread/mod.rs:473:30
 129: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/ops/function.rs:227:5
 130: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/alloc/src/boxed.rs:1546:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/alloc/src/boxed.rs:1546:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys/unix/thread.rs:71:17
 131: start_thread
 132: clone


Thread 'tokio-runtime-worker' panicked at 'assertion failed: res.is_ok()', /home/ziel/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/80235e9/runtime/common/src/slots.rs:284

This is a bug. Please report it at:

	https://github.com/AcalaNetwork/Acala/issues
```

**Comment by xlc** [comment]
This is a polkadot issue. How did you run the node?

**Comment by zie1ony** [comment]
```
RUST_LOG=info cargo run
```

**Comment by xlc** [comment]
closed as this is upstream issue
